In [1]:
a = np.random.randn(3,3)
b = np.random.randn(3,1)
c = a*b

NameError: name 'np' is not defined

In [4]:
import numpy as np
a = np.random.randn(3,3)
b = np.random.randn(3,1)
c = a*b
print(c)

[[ 0.11464908 -1.05371756  0.86825759]
 [-0.78636328  1.684653   -3.30693426]
 [-0.4571846  -1.02777172 -0.98389666]]


In [14]:
import numpy as np
x = np.array([
    [0,3,4],
    [2,6,4]
])

x_norm = np.linalg.norm(x, axis = 0, keepdims = True)
print (x_norm)

[[ 2.          6.70820393  5.65685425]]
