In [6]:
import numpy as np

z = np.array([[1, 2, 3, 4],
          [5, 6, 7, 8],
          [9, 10, 11, 12],
          ])
print(z.shape)

(3, 4)


In [7]:
z

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
print(z.reshape(-1))

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [9]:
print(z.shape[0])

3


In [10]:
print(z.reshape(z.shape[0], -1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
print(z.reshape(z.shape[0], -1).T)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [12]:
print(z.reshape(z.shape[1], -1))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
print(z.reshape(z.shape[0], 1))

ValueError: cannot reshape array of size 12 into shape (3,1)

In [14]:
print(z.reshape(-1, 1))

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


In [ ]:
#結論，reshape中-1==未知，會根據前/後面隻已知值調整